version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 55555
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: std_2414_exam
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/database.sql:/docker-entrypoint-initdb.d/database.sql
      #- ./app/init.sh:/docker-entrypoint-initdb.d/init.sh  # Добавляем скрипт
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 3s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy



  
volumes:
  mysql_data:
  database.sql:
