version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 55555
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: std_2414_exam
    volumes:
      - mysql_data:/var/lib/mysql
      - database.sql:/docker-entrypoint-initdb.d/databse.sql
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - web:/app

volumes:
  mysql_data:
  web:
  database.sql:
