# Используем базовый образ Ubuntu
FROM ubuntu:20.04ds

# Устанавливаем часовойds пояс (например, Europe/Moscow)
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
fd
# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    pkg-config \
    python3 \
    python3-pip \
    mysql-server \
    libmysqlclient-dev

# Копируем код приложения
COPY . app/app
WORKDIR app/app

# Устанавливаем Python-зависимости
RUN pip3 install -r requirements.txt

# Настраиваем MySQL
RUN service mysql start && \
    mysql -e "CREATE DATABASE std_2414_exam;" && \
    mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY '12345';" && \
    mysql -e "GRANT ALL PRIVILEGES ON std_2414_exam.* TO 'root'@'%';" && \
    mysql -e "FLUSH PRIVILEGES; ds"

# Устанавливаем переменные окружения для Flask
ENV FLASK_APP=app/app.py
ENV FLASK_ENV=development
ds
# Запускаем MySQL и Flask-приложение
CMD service mysql start && flask run --host=0.0.0.0 --port=5000
EXPOSE 5000
