version: '3.8'

services:
  db:
    image: localhost:5555/library/mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/database/database.sql:/docker-entrypoint-initdb.d/database.sql
      #- ./app/init.sh:/docker-entrypoint-initdb.d/init.sh  # Добавляем скрипт
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      interval: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5050:5000"
    depends_on:
      db:
        condition: service_healthy



  
volumes:
  mysql_data:
  database.sql:
